language: cpp
sudo: required
dist: trusty
compiler: g++
install: true
before_script:
    - g++ --version
script:
    - make clean
    - make test

addons:
  apt:
    packages:
    - g++-4.9
    - gcc-4.9
    - libopenmpi-dev
    - opencl-headers
    - fglrx-core
    - beignet
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
 
